--  Stub generated by OpenGEODE.
--  You can edit this file, it will not be overwritten

package body Thermostat_RI is
   procedure setOnOff (Command : in out asn1SccHeater_On_Off) is null;
end Thermostat_RI;