/* Body file for function GUI
 * Generated by TASTE on 2021-05-17 23:04:53
 * You can edit this file, it will not be overwritten
 * Provided interfaces : Update
 * Required interfaces : 
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = any
 *   |_ Taste::coordinates = 225033 58109 266135 79841
 * Timers              : 
 */

#include "gui.h"
//#include <stdio.h>


void gui_startup(void)
{
   // Write your initialisation code, but DO NOT CALL REQUIRED INTERFACES
   // puts ("[GUI] Startup");
}

void gui_PI_Update
      (const asn1SccOBSW_DP_Data *IN_alldata)

{
   // Write your code here
}


