/* Body file for function PrettyFormatter
 * Generated by TASTE on 2021-05-21 15:43:53
 * You can edit this file, it will not be overwritten
 * Provided interfaces : sendTM
 * Required interfaces : printAllData
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = any
 *   |_ Taste::coordinates = 250580 83853 286503 106642
 * Timers              : 
 */

#include "prettyformatter.h"
//#include <stdio.h>


void prettyformatter_startup(void)
{
   // Write your initialisation code, but DO NOT CALL REQUIRED INTERFACES
   // puts ("[PrettyFormatter] Startup");
}

void prettyformatter_PI_sendTM(void)
{
   // Write your code here
}


