/* Body file for function Watchdog
 * Generated by TASTE on 2021-07-07 13:40:28
 * You can edit this file, it will not be overwritten
 * Provided interfaces : KickTheDog
 * Required interfaces : 
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = any
 *   |_ Taste::coordinates = 193046 62860 216706 68336
 * Timers              : 
 */

#include "watchdog.h"
#include "Context-watchdog.h"
#include <stdio.h>

#include <stdlib.h>
#include <unistd.h>
#include <fcntl.h>
#include <sys/ioctl.h>
#include <linux/watchdog.h>

static int fd = -1;

void watchdog_startup(void)
{
   // Write your initialisation code, but DO NOT CALL REQUIRED INTERFACES
    puts ("[Watchdog] Startup");
    
    fd = open("/dev/watchdog", O_WRONLY);
    if (fd < 0) {
        perror("[Watchdog] Started");
        return;
    }
    
    int timeout = watchdog_ctxt.timeout;
    if (ioctl(fd, WDIOC_SETTIMEOUT, &timeout) < 0) {
        perror("[Watchdog] set watchdog timeout");
    }
}

void watchdog_PI_KickTheDog(void)
{
   // Write your code here
    if (fd >= 0) {
        if (ioctl(fd, WDIOC_KEEPALIVE, 0) < 0) {
            perror("[Watchdog] kick watchdog");
        } else {
            puts("                         /");
            puts("[Watchdog] Dog kicked /\\/");
            puts("                     /   ");
        }
    }
}

void watchdog_PI_stop( void ) {
    if ( fd >= 0 && (write(fd, "V", 1) >= 0) ) {
        close(fd);
        fd = -1;
        puts("@@@@@@@@@@@@@@@@@@@@@@@ Watchdog @@@@@@@@@@@@@@@@@@@@@@");
    } else {
        perror("stop watchdog");
    }
}
