
/* Header file for function Thermostat in CPP language
 * Generated by TASTE on 2021-06-02 09:39:55
 * Context Parameters present : NO
 * Provided interfaces : notifyTempChanged
 * Required interfaces : setPowerH2
 * User-defined properties for this function:
  *  |_ Taste::Active_Interfaces = any
  *  |_ Taste::coordinates = 231205 62919 261920 74258
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __unix__
   #include <stdlib.h>
   #include <stdio.h>
#endif

void thermostat_startup(void);

/* Provided interfaces */
void thermostat_PI_notifyTempChanged( const asn1SccT_Float * );

/* Required interfaces */
extern void thermostat_RI_setPowerH2( const asn1SccT_Float * );


#ifdef __cplusplus
}
#endif

