--  DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
--  Generated by TASTE (Kazoo template templates/skeletons/ada-ri-source/function.tmplt)
--  2021-06-05 19:03:24
with Tasec_Lab_B2space_Dataview; use Tasec_Lab_B2space_Dataview;
with Taste_Basictypes;           use Taste_Basictypes;

package Thermostat_RI is

   procedure Setonoffh2 (Command : in out asn1SccHeater_On_Off);

end Thermostat_RI;
