--  Stub generated by OpenGEODE.
--  You can edit this file, it will not be overwritten

package body Heattransferlab_RI is
   procedure RetreiveAllData (Alldata : out asn1SccOBSW_DP_Data) is null;
   procedure setOnOffH1 (Command : in out asn1SccHeater_On_Off) is null;
   procedure setPowerH1 (Power : in out asn1SccT_Float) is null;
   procedure SET_f1_max_time (Val : in out asn1SccT_UInt32) is null;
   procedure RESET_f1_max_time is null;
   procedure SET_f2_max_time (Val : in out asn1SccT_UInt32) is null;
   procedure RESET_f2_max_time is null;
end Heattransferlab_RI;