
/* Header file for function Experimenter in GUI language
 * Generated by TASTE on 2021-05-17 14:44:52
 * Context Parameters present : NO
 * Provided interfaces : getAllData
 * Required interfaces : 
 * User-defined properties for this function:
  *  |_ Taste::Active_Interfaces = any
  *  |_ Taste::coordinates = 222733 52021 251394 106351
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __unix__
   #include <stdlib.h>
   #include <stdio.h>
#endif

void experimenter_startup(void);

/* Provided interfaces */
void experimenter_PI_getAllData( const asn1SccOBSW_DP_Data * );

/* Required interfaces */



#ifdef __cplusplus
}
#endif

