// Body file for function HKAndMonitoring
// Generated by TASTE on 2021-05-21 15:27:24
// You can edit this file, it will not be overwritten
// Provided interfaces : Tick
// Required interfaces : RetreiveAllData, SendData
// User-defined properties for this function:
//   |_ Taste::Active_Interfaces = any
//   |_ Taste::coordinates = 229758 93383 270229 106296
// Timers              : 

#include "hkandmonitoring.h"
#include "hkandmonitoring_state.h"
//#include <iostream>

// Define and use function state inside this context structure
// avoid defining global/static variable elsewhere
hkandmonitoring_state ctxt_hkandmonitoring;


void hkandmonitoring_startup(void)
{
   // Write your initialisation code, but DO NOT CALL REQUIRED INTERFACES
   // std::cout << "[HKAndMonitoring] Startup" << std::endl;
}

void hkandmonitoring_PI_Tick(void)
{
   // Write your code here
}


