/* ASN.1 System configuration file for function HeatTransferLab
 * Generated by TASTE on 2021-07-06 13:54:18
 */
#define __NEED_HTL_Config_NATIVE
#define __NEED_HTL_State_NATIVE
#define __NEED_HTL_State_NATIVE
