/* ASN.1 System configuration file for function HeatTransferLab
 * Generated by TASTE on 2021-06-28 15:23:52
 */
#define __NEED_HTL_Config_NATIVE
#define __NEED_HTL_State_NATIVE
#define __NEED_HTL_State_NATIVE
