/* Body file for function HeatTransferLab
 * Generated by TASTE on 2021-06-05 19:03:24
 * Provided interfaces : tick
 * Required interfaces : RetreiveAllData, setOnOffH1, setPowerH1
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = any
 *   |_ Taste::coordinates = 160859 58529 196077 70443
 * Timers              : 
 */
#include "heattransferlab_vm_if.h"
#ifdef __unix__
   #include <stdio.h>
#endif



extern void adainit(void);

extern void init_datapool(void);
extern unsigned datapool_initialized;
extern void init_heater1(void);
extern unsigned heater1_initialized;
extern void init_heater1(void);
extern unsigned heater1_initialized;
unsigned heattransferlab_initialized = 0;
void init_heattransferlab(void)
{
   if (0 == heattransferlab_initialized) {
      heattransferlab_initialized = 1;
      // Initialize Ada runtime to call elaboration functions
      adainit();
      // Iterate over all synchronous RIs, and call their parent's
      // init function. Multiple calls are prevented by the "init" guard.
      if (0 == datapool_initialized) {
          init_datapool();
      }
      if (0 == heater1_initialized) {
          init_heater1();
      }
      if (0 == heater1_initialized) {
          init_heater1();
      }
#ifdef __unix__
      puts ("[TASTE] Initialization completed for function HeatTransferLab");
#endif
      heattransferlab_initialized = 2;
   }
}
void heattransferlab_tick()
{
   //  Directly call user code, no parameters to pass
   extern void heattransferlab_PI_tick(void);
   heattransferlab_PI_tick();
   // puts ("heattransferlab_tick called");
}

