--  DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
--  Generated by TASTE (Kazoo template templates/skeletons/ada-ri-source/function.tmplt)
--  2021-06-21 01:56:25
--  Timers:

with Tasec_Lab_B2space_Dataview; use Tasec_Lab_B2space_Dataview;
with Taste_Basictypes;           use Taste_Basictypes;

package Systemhandler_RI is

   procedure Stop_Dl;
   procedure Stop_Dm;
   procedure Stop_Iic;

end Systemhandler_RI;
