/* C++ Body file for function type FunctionInstance1
 * Generated by TASTE on 2021-05-18 19:10:51
 * You can edit this file, it will not be overwritten
 * Provided interfaces : getPower, setPower
 * Required interfaces : 
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = any
 *   |_ Taste::coordinates = 80300 137307 104767 146688
 *   |_ Taste::is_Instance_Of = Heater::IV::Heater::Heater.others
 *   |_ Taste::is_Instance_Of2 = Heater.others
 * Timers              : 
 */

#include "functioninstance1.h"
#include "heater.h"

// Include Context Parameters (constants defined in the Interface View)
#include "Context-functioninstance1.h"

// Declaration of the function instance
extern heater FunctionInstance1 (functioninstance1_ctxt);

extern "C" void functioninstance1_startup()
{
   FunctionInstance1.startup();
}

extern "C" void functioninstance1_PI_getPower (asn1SccT_Float *power)
{
   FunctionInstance1.getPower(power);
}
extern "C" void functioninstance1_PI_setPower (const asn1SccT_Float *power)
{
   FunctionInstance1.setPower(power);
}
