/* Body file for function DataLogger
 * Generated by TASTE on 2021-06-07 19:06:14
 * Provided interfaces : RecordAllData
 * Required interfaces : RetreiveAllData
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = any
 *   |_ Taste::coordinates = 201685 59359 226750 70109
 * Timers              : 
 */
#include "datalogger_vm_if.h"
#ifdef __unix__
   #include <stdio.h>
#endif




extern void init_datapool(void);
extern unsigned datapool_initialized;
unsigned datalogger_initialized = 0;
void init_datalogger(void)
{
   if (0 == datalogger_initialized) {
      datalogger_initialized = 1;
      // Call user code startup function
      extern void datalogger_startup(void);
      datalogger_startup();
      // Iterate over all synchronous RIs, and call their parent's
      // init function. Multiple calls are prevented by the "init" guard.
      if (0 == datapool_initialized) {
          init_datapool();
      }
#ifdef __unix__
      puts ("[TASTE] Initialization completed for function DataLogger");
#endif
      datalogger_initialized = 2;
   }
}
void datalogger_RecordAllData()
{
   //  Directly call user code, no parameters to pass
   extern void datalogger_PI_RecordAllData(void);
   datalogger_PI_RecordAllData();
   // puts ("datalogger_recordalldata called");
}

