#ifndef GENERATED_ASN1SCC_Context_datapool_H
#define GENERATED_ASN1SCC_Context_datapool_H
/*
Code automatically generated by asn1scc tool
*/
#include "asn1crt.h"
#include "asn1crt_encoding.h"

#include "dataview-uniq.h"

#ifdef  __cplusplus
extern "C" {
#endif


/*-- asn1SccContext_datapool --------------------------------------------*/
typedef struct {
    asn1SccT_Double maxoutdatedsecs;

} asn1SccContext_datapool;

flag asn1SccContext_datapool_Equal(const asn1SccContext_datapool* pVal1, const asn1SccContext_datapool* pVal2);

void asn1SccContext_datapool_Initialize(asn1SccContext_datapool* pVal);

#define ERR_CONTEXT_DATAPOOL		8506  /**/
#define ERR_CONTEXT_DATAPOOL_MAXOUTDATEDSECS_2		8499  /**/
flag asn1SccContext_datapool_IsConstraintValid(const asn1SccContext_datapool* pVal, int* pErrCode);

#define ERR_UPER_ENCODE_CONTEXT_DATAPOOL		8507  /**/
#define ERR_UPER_ENCODE_CONTEXT_DATAPOOL_MAXOUTDATEDSECS_2		8500  /**/
#define asn1SccContext_datapool_REQUIRED_BYTES_FOR_ENCODING       13 
#define asn1SccContext_datapool_REQUIRED_BITS_FOR_ENCODING        104

flag asn1SccContext_datapool_Encode(const asn1SccContext_datapool* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_CONTEXT_DATAPOOL		8508  /**/
#define ERR_UPER_DECODE_CONTEXT_DATAPOOL_MAXOUTDATEDSECS_2		8501  /**/
flag asn1SccContext_datapool_Decode(asn1SccContext_datapool* pVal, BitStream* pBitStrm, int* pErrCode);

#define ERR_ACN_ENCODE_CONTEXT_DATAPOOL		8509  /**/
#define ERR_ACN_ENCODE_CONTEXT_DATAPOOL_MAXOUTDATEDSECS_2		8502  /**/
#define asn1SccContext_datapool_REQUIRED_BYTES_FOR_ACN_ENCODING       13 
#define asn1SccContext_datapool_REQUIRED_BITS_FOR_ACN_ENCODING        104

flag asn1SccContext_datapool_ACN_Encode(const asn1SccContext_datapool* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_CONTEXT_DATAPOOL		8510  /**/
#define ERR_ACN_DECODE_CONTEXT_DATAPOOL_MAXOUTDATEDSECS_2		8503  /**/
flag asn1SccContext_datapool_ACN_Decode(asn1SccContext_datapool* pVal, BitStream* pBitStrm, int* pErrCode);

extern const asn1SccContext_datapool datapool_ctxt; 

/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */

 


#ifdef  __cplusplus
}

#endif

#endif
