#ifndef GENERATED_ASN1SCC_Context_watchdog_H
#define GENERATED_ASN1SCC_Context_watchdog_H
/*
Code automatically generated by asn1scc tool
*/
#include "asn1crt.h"
#include "asn1crt_encoding.h"

#include "dataview-uniq.h"

#ifdef  __cplusplus
extern "C" {
#endif


/*-- asn1SccContext_watchdog --------------------------------------------*/
typedef struct {
    asn1SccWD_TIMEOUT timeout;

} asn1SccContext_watchdog;

flag asn1SccContext_watchdog_Equal(const asn1SccContext_watchdog* pVal1, const asn1SccContext_watchdog* pVal2);

void asn1SccContext_watchdog_Initialize(asn1SccContext_watchdog* pVal);

#define ERR_CONTEXT_WATCHDOG		8779  /**/
#define ERR_CONTEXT_WATCHDOG_TIMEOUT_2		8772  /**/
flag asn1SccContext_watchdog_IsConstraintValid(const asn1SccContext_watchdog* pVal, int* pErrCode);

#define ERR_UPER_ENCODE_CONTEXT_WATCHDOG		8780  /**/
#define ERR_UPER_ENCODE_CONTEXT_WATCHDOG_TIMEOUT_2		8773  /**/
#define asn1SccContext_watchdog_REQUIRED_BYTES_FOR_ENCODING       1 
#define asn1SccContext_watchdog_REQUIRED_BITS_FOR_ENCODING        4

flag asn1SccContext_watchdog_Encode(const asn1SccContext_watchdog* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_CONTEXT_WATCHDOG		8781  /**/
#define ERR_UPER_DECODE_CONTEXT_WATCHDOG_TIMEOUT_2		8774  /**/
flag asn1SccContext_watchdog_Decode(asn1SccContext_watchdog* pVal, BitStream* pBitStrm, int* pErrCode);

#define ERR_ACN_ENCODE_CONTEXT_WATCHDOG		8782  /**/
#define ERR_ACN_ENCODE_CONTEXT_WATCHDOG_TIMEOUT_2		8775  /**/
#define asn1SccContext_watchdog_REQUIRED_BYTES_FOR_ACN_ENCODING       1 
#define asn1SccContext_watchdog_REQUIRED_BITS_FOR_ACN_ENCODING        4

flag asn1SccContext_watchdog_ACN_Encode(const asn1SccContext_watchdog* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_CONTEXT_WATCHDOG		8783  /**/
#define ERR_ACN_DECODE_CONTEXT_WATCHDOG_TIMEOUT_2		8776  /**/
flag asn1SccContext_watchdog_ACN_Decode(asn1SccContext_watchdog* pVal, BitStream* pBitStrm, int* pErrCode);

extern const asn1SccContext_watchdog watchdog_ctxt; 

/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */

 


#ifdef  __cplusplus
}

#endif

#endif
