#ifndef GENERATED_ASN1SCC_Context_pressuresensors_H
#define GENERATED_ASN1SCC_Context_pressuresensors_H
/*
Code automatically generated by asn1scc tool
*/
#include "asn1crt.h"
#include "asn1crt_encoding.h"

#include "dataview-uniq.h"

#ifdef  __cplusplus
extern "C" {
#endif


/*-- asn1SccContext_pressuresensors --------------------------------------------*/
typedef struct {
    asn1SccSPI_ID ps1_id;
    asn1SccSPI_ID ps2_id;

} asn1SccContext_pressuresensors;

flag asn1SccContext_pressuresensors_Equal(const asn1SccContext_pressuresensors* pVal1, const asn1SccContext_pressuresensors* pVal2);

void asn1SccContext_pressuresensors_Initialize(asn1SccContext_pressuresensors* pVal);

#define ERR_CONTEXT_PRESSURESENSORS		8121  /**/
#define ERR_CONTEXT_PRESSURESENSORS_PS1_ID_2		8072  /**/
#define ERR_CONTEXT_PRESSURESENSORS_PS2_ID_2		8114  /**/
flag asn1SccContext_pressuresensors_IsConstraintValid(const asn1SccContext_pressuresensors* pVal, int* pErrCode);

#define ERR_UPER_ENCODE_CONTEXT_PRESSURESENSORS		8122  /**/
#define ERR_UPER_ENCODE_CONTEXT_PRESSURESENSORS_PS1_ID_2		8073  /**/
#define ERR_UPER_ENCODE_CONTEXT_PRESSURESENSORS_PS2_ID_2		8115  /**/
#define asn1SccContext_pressuresensors_REQUIRED_BYTES_FOR_ENCODING       4 
#define asn1SccContext_pressuresensors_REQUIRED_BITS_FOR_ENCODING        32

flag asn1SccContext_pressuresensors_Encode(const asn1SccContext_pressuresensors* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_CONTEXT_PRESSURESENSORS		8123  /**/
#define ERR_UPER_DECODE_CONTEXT_PRESSURESENSORS_PS1_ID_2		8074  /**/
#define ERR_UPER_DECODE_CONTEXT_PRESSURESENSORS_PS2_ID_2		8116  /**/
flag asn1SccContext_pressuresensors_Decode(asn1SccContext_pressuresensors* pVal, BitStream* pBitStrm, int* pErrCode);

#define ERR_ACN_ENCODE_CONTEXT_PRESSURESENSORS		8124  /**/
#define ERR_ACN_ENCODE_CONTEXT_PRESSURESENSORS_PS1_ID_2		8075  /**/
#define ERR_ACN_ENCODE_CONTEXT_PRESSURESENSORS_PS2_ID_2		8117  /**/
#define asn1SccContext_pressuresensors_REQUIRED_BYTES_FOR_ACN_ENCODING       4 
#define asn1SccContext_pressuresensors_REQUIRED_BITS_FOR_ACN_ENCODING        32

flag asn1SccContext_pressuresensors_ACN_Encode(const asn1SccContext_pressuresensors* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_CONTEXT_PRESSURESENSORS		8125  /**/
#define ERR_ACN_DECODE_CONTEXT_PRESSURESENSORS_PS1_ID_2		8076  /**/
#define ERR_ACN_DECODE_CONTEXT_PRESSURESENSORS_PS2_ID_2		8118  /**/
flag asn1SccContext_pressuresensors_ACN_Decode(asn1SccContext_pressuresensors* pVal, BitStream* pBitStrm, int* pErrCode);

extern const asn1SccContext_pressuresensors pressuresensors_ctxt; 

/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */

 


#ifdef  __cplusplus
}

#endif

#endif
