/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>

#include "asn1crt_encoding.h"
#include "asn1crt_encoding_uper.h"
#include "asn1crt_encoding_acn.h"

#include "Context-gpsreader.h"

const asn1SccContext_gpsreader gpsreader_ctxt = {
    .max_retries = 5,
    .waiting_time_per_retry_us = 300000
};


flag asn1SccContext_gpsreader_Equal(const asn1SccContext_gpsreader* pVal1, const asn1SccContext_gpsreader* pVal2)
{
	flag ret=TRUE;

    ret = (pVal1->max_retries == pVal2->max_retries);

    if (ret) {
        ret = (pVal1->waiting_time_per_retry_us == pVal2->waiting_time_per_retry_us);

    }

	return ret;

}

void asn1SccContext_gpsreader_Initialize(asn1SccContext_gpsreader* pVal)
{
	(void)pVal;



	/*set max_retries */
	asn1SccT_UInt32_Initialize((&(pVal->max_retries)));
	/*set waiting_time_per_retry_us */
	asn1SccT_UInt32_Initialize((&(pVal->waiting_time_per_retry_us)));
}

flag asn1SccContext_gpsreader_IsConstraintValid(const asn1SccContext_gpsreader* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = asn1SccT_UInt32_IsConstraintValid((&(pVal->max_retries)), pErrCode);
    if (ret) {
        ret = asn1SccT_UInt32_IsConstraintValid((&(pVal->waiting_time_per_retry_us)), pErrCode);
    }

	return ret;
}

flag asn1SccContext_gpsreader_Encode(const asn1SccContext_gpsreader* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	ret = bCheckConstraints ? asn1SccContext_gpsreader_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode max_retries */
	    ret = asn1SccT_UInt32_Encode((&(pVal->max_retries)), pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode waiting_time_per_retry_us */
	        ret = asn1SccT_UInt32_Encode((&(pVal->waiting_time_per_retry_us)), pBitStrm, pErrCode, FALSE);
	    }
    } /*COVERAGE_IGNORE*/

	
    return ret;
}

flag asn1SccContext_gpsreader_Decode(asn1SccContext_gpsreader* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	/*Decode max_retries */
	ret = asn1SccT_UInt32_Decode((&(pVal->max_retries)), pBitStrm, pErrCode);
	if (ret) {
	    /*Decode waiting_time_per_retry_us */
	    ret = asn1SccT_UInt32_Decode((&(pVal->waiting_time_per_retry_us)), pBitStrm, pErrCode);
	}

	return ret  && asn1SccContext_gpsreader_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccContext_gpsreader_ACN_Encode(const asn1SccContext_gpsreader* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

	ret = bCheckConstraints ? asn1SccContext_gpsreader_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode max_retries */
	    ret = asn1SccT_UInt32_ACN_Encode((&(pVal->max_retries)), pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode waiting_time_per_retry_us */
	        ret = asn1SccT_UInt32_ACN_Encode((&(pVal->waiting_time_per_retry_us)), pBitStrm, pErrCode, FALSE);
	    }

    } /*COVERAGE_IGNORE*/

	
    return ret;
}

flag asn1SccContext_gpsreader_ACN_Decode(asn1SccContext_gpsreader* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	/*Decode max_retries */
	ret = asn1SccT_UInt32_ACN_Decode((&(pVal->max_retries)), pBitStrm, pErrCode);
	if (ret) {
	    /*Decode waiting_time_per_retry_us */
	    ret = asn1SccT_UInt32_ACN_Decode((&(pVal->waiting_time_per_retry_us)), pBitStrm, pErrCode);
	}


    return ret && asn1SccContext_gpsreader_IsConstraintValid(pVal, pErrCode);
}

