#ifndef GENERATED_ASN1SCC_Context_pressuresensors_H
#define GENERATED_ASN1SCC_Context_pressuresensors_H
/*
Code automatically generated by asn1scc tool
*/
#include "asn1crt.h"
#include "asn1crt_encoding.h"

#include "dataview-uniq.h"

#ifdef  __cplusplus
extern "C" {
#endif


/*-- asn1SccContext_pressuresensors --------------------------------------------*/
typedef struct {
    asn1SccSPI_ID ps1_id;
    asn1SccSPI_ID ps2_id;

} asn1SccContext_pressuresensors;

flag asn1SccContext_pressuresensors_Equal(const asn1SccContext_pressuresensors* pVal1, const asn1SccContext_pressuresensors* pVal2);

void asn1SccContext_pressuresensors_Initialize(asn1SccContext_pressuresensors* pVal);

#define ERR_CONTEXT_PRESSURESENSORS		8191  /**/
#define ERR_CONTEXT_PRESSURESENSORS_PS1_ID_2		8142  /**/
#define ERR_CONTEXT_PRESSURESENSORS_PS2_ID_2		8184  /**/
flag asn1SccContext_pressuresensors_IsConstraintValid(const asn1SccContext_pressuresensors* pVal, int* pErrCode);

#define ERR_UPER_ENCODE_CONTEXT_PRESSURESENSORS		8192  /**/
#define ERR_UPER_ENCODE_CONTEXT_PRESSURESENSORS_PS1_ID_2		8143  /**/
#define ERR_UPER_ENCODE_CONTEXT_PRESSURESENSORS_PS2_ID_2		8185  /**/
#define asn1SccContext_pressuresensors_REQUIRED_BYTES_FOR_ENCODING       4 
#define asn1SccContext_pressuresensors_REQUIRED_BITS_FOR_ENCODING        32

flag asn1SccContext_pressuresensors_Encode(const asn1SccContext_pressuresensors* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_CONTEXT_PRESSURESENSORS		8193  /**/
#define ERR_UPER_DECODE_CONTEXT_PRESSURESENSORS_PS1_ID_2		8144  /**/
#define ERR_UPER_DECODE_CONTEXT_PRESSURESENSORS_PS2_ID_2		8186  /**/
flag asn1SccContext_pressuresensors_Decode(asn1SccContext_pressuresensors* pVal, BitStream* pBitStrm, int* pErrCode);

#define ERR_ACN_ENCODE_CONTEXT_PRESSURESENSORS		8194  /**/
#define ERR_ACN_ENCODE_CONTEXT_PRESSURESENSORS_PS1_ID_2		8145  /**/
#define ERR_ACN_ENCODE_CONTEXT_PRESSURESENSORS_PS2_ID_2		8187  /**/
#define asn1SccContext_pressuresensors_REQUIRED_BYTES_FOR_ACN_ENCODING       4 
#define asn1SccContext_pressuresensors_REQUIRED_BITS_FOR_ACN_ENCODING        32

flag asn1SccContext_pressuresensors_ACN_Encode(const asn1SccContext_pressuresensors* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_CONTEXT_PRESSURESENSORS		8195  /**/
#define ERR_ACN_DECODE_CONTEXT_PRESSURESENSORS_PS1_ID_2		8146  /**/
#define ERR_ACN_DECODE_CONTEXT_PRESSURESENSORS_PS2_ID_2		8188  /**/
flag asn1SccContext_pressuresensors_ACN_Decode(asn1SccContext_pressuresensors* pVal, BitStream* pBitStrm, int* pErrCode);

extern const asn1SccContext_pressuresensors pressuresensors_ctxt; 

/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */

 


#ifdef  __cplusplus
}

#endif

#endif
