/* Body file for function PrettyFormat
 * Generated by TASTE on 2021-05-31 23:39:55
 * You can edit this file, it will not be overwritten
 * Provided interfaces : tm
 * Required interfaces : Attitude_Data, Environmental_Data, HTL_Data
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = any
 *   |_ Taste::coordinates = 63658 52504 89323 71325
 * Timers              : 
 */

#include "prettyformat.h"
//#include <stdio.h>


void prettyformat_startup(void)
{
   // Write your initialisation code, but DO NOT CALL REQUIRED INTERFACES
   // puts ("[PrettyFormat] Startup");
}

void prettyformat_PI_tm(void)
{
   // Write your code here
}


