/* Body file for function Heater2
 * Generated by TASTE on 2021-05-19 10:53:28
 * You can edit this file, it will not be overwritten
 * Provided interfaces : getPowerH2, setPowerH2
 * Required interfaces : 
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = any
 *   |_ Taste::coordinates = 78082 159857 103722 169558
 * Timers              : 
 */

#include "heater2.h"
//#include <stdio.h>


void heater2_startup(void)
{
   // Write your initialisation code, but DO NOT CALL REQUIRED INTERFACES
   // puts ("[Heater2] Startup");
}

void heater2_PI_getPowerH2
      (asn1SccT_Float *OUT_power)

{
   // Write your code here
}
void heater2_PI_setPowerH2
      (const asn1SccT_Float *IN_power)

{
   // Write your code here
}


