################################################################################
include ../Makevars.mk

# Name of the static library to be created
NAME_LIB=equipementHandlers.a
# Name of the executable
NAME_BIN=
# Name of the test
NAME_TEST=
# Additional libraries to be loaded when compiling.
LDLIBS  = -lgps -lm -lgpiodcxx -lpigpiod_if2 -lrt

.PHONY: all
all:
	$(info Nothing to do in a 3rd party library.)

#include ../Makerules.mk
################################################################################
