/* ASN.1 System configuration file for function DataPool
 * Generated by TASTE on 2021-06-21 01:56:25
 */
#define __NEED_OBSW_DP_Data_NATIVE
#define __NEED_OBSW_DP_Data_NATIVE
#define __NEED_OBSW_DP_Filter_NATIVE
#define __NEED_OBSW_DP_SingleData_NATIVE
#define __NEED_T_Double_NATIVE
#define __NEED_T_Double_NATIVE
