/* ASN.1 System configuration file for function DataPool
 * Generated by TASTE on 2021-06-05 19:03:24
 */
#define __NEED_OBSW_DP_Data_NATIVE
#define __NEED_OBSW_DP_Data_NATIVE
#define __NEED_T_Double_NATIVE
#define __NEED_T_Double_NATIVE
