--  DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
--  Generated by TASTE (Kazoo template templates/skeletons/ada-ri-source/function.tmplt)
--  2021-07-08 21:13:24
--  Timers:

with Tasec_Lab_B2space_Dataview; use Tasec_Lab_B2space_Dataview;
with Taste_Basictypes;           use Taste_Basictypes;

package Heattransferlab_RI is

   procedure Kickthedog;
   procedure Recordhtlparams (Htl_State : in out asn1SccHtl_State; F1_Max_Time : in out asn1SccT_Double; F2_Max_Time : in out asn1SccT_Double);
   procedure Recoverhtlparams (Htl_State : out asn1SccHtl_State; F1_Max_Time : out asn1SccT_Double; F2_Max_Time : out asn1SccT_Double);
   procedure Retreivesingledata (Filter : in out asn1SccObsw_Dp_Filter; Single_Data : out asn1SccObsw_Dp_Singledata);
   procedure Stopsystem;
   procedure Gettime (Gps_Time : out asn1SccT_Double; Mission_Time : out asn1SccT_Double);
   procedure Setpowerh2 (Power : in out asn1SccT_Float);

end Heattransferlab_RI;
