/* Body file for function TC
 * Generated by TASTE on 2021-06-29 11:21:07
 * Provided interfaces : tc
 * Required interfaces : StopSystem, configureParameters, setPowerH1, setPowerH2
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = any
 *   |_ Taste::coordinates = 126771 68013 152282 83447
 * Timers              : 
 */
#include "tc_vm_if.h"
#include "C_ASN1_Types.h"
#ifdef __unix__
   #include <stdio.h>
#endif




extern void init_systemhandler(void);
extern unsigned systemhandler_initialized;
extern void init_heattransferlab(void);
extern unsigned heattransferlab_initialized;
extern void init_heater1(void);
extern unsigned heater1_initialized;
extern void init_heater2(void);
extern unsigned heater2_initialized;
unsigned tc_initialized = 0;
void init_tc(void)
{
   if (0 == tc_initialized) {
      tc_initialized = 1;
      // Call user code startup function
      extern void tc_startup(void);
      tc_startup();
      // Iterate over all synchronous RIs, and call their parent's
      // init function. Multiple calls are prevented by the "init" guard.
      if (0 == systemhandler_initialized) {
          init_systemhandler();
      }
      if (0 == heattransferlab_initialized) {
          init_heattransferlab();
      }
      if (0 == heater1_initialized) {
          init_heater1();
      }
      if (0 == heater2_initialized) {
          init_heater2();
      }
#ifdef __unix__
      puts ("[TASTE] Initialization completed for function TC");
#endif
      tc_initialized = 2;
   }
}
void tc_tc
      (const char *IN_tc, size_t IN_tc_len)

{

   static asn1SccTC IN_TC;
#ifdef __unix__
   asn1SccTC_Initialize(&IN_TC);
#endif
   if (0 != Decode_UPER_TC (&IN_TC, (void *)IN_tc, IN_tc_len)) {
      #ifdef __unix__
         puts("Error decoding TC in function TC_tc");
      #endif
      return;
   }

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void tc_PI_tc
      (const asn1SccTC *);




   // Call user code
   tc_PI_tc (&IN_TC);

}

