/* Body file for function Anemometer
 * Generated by TASTE on 2021-06-05 19:03:24
 * Provided interfaces : getTotalPulses
 * Required interfaces : 
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = any
 *   |_ Taste::coordinates = 175029 143576 203645 153278
 * Timers              : 
 */
#include "anemometer_vm_if.h"
#include "C_ASN1_Types.h"
#ifdef __unix__
   #include <stdio.h>
#endif




unsigned anemometer_initialized = 0;
void init_anemometer(void)
{
   if (0 == anemometer_initialized) {
      anemometer_initialized = 1;
      // Call user code startup function
      extern void anemometer_startup(void);
      anemometer_startup();
#ifdef __unix__
      puts ("[TASTE] Initialization completed for function Anemometer");
#endif
      anemometer_initialized = 2;
   }
}
void anemometer_getTotalPulses
      (char *OUT_noftotalpulses, size_t *OUT_noftotalpulses_len)

{

   static asn1SccT_UInt64 OUT_NOFTOTALPULSES;
#ifdef __unix__
   asn1SccT_UInt64_Initialize(&OUT_NOFTOTALPULSES);
#endif

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void anemometer_PI_getTotalPulses
      (asn1SccT_UInt64 *);




   // Call user code
   anemometer_PI_getTotalPulses (&OUT_NOFTOTALPULSES);

   *OUT_noftotalpulses_len = Encode_NATIVE_T_UInt64
      ((void *)OUT_noftotalpulses,
       sizeof (asn1SccT_UInt64),
       &OUT_NOFTOTALPULSES);
}

