/* ASN.1 System configuration file for function PT1000Sensors
 * Generated by TASTE on 2021-07-13 16:37:57
 */
#define __NEED_PT1000s_All_Data_NATIVE
#define __NEED_T_Float_NATIVE
#define __NEED_T_Float_NATIVE
#define __NEED_T_Float_NATIVE
#define __NEED_Content_Validity_NATIVE
#define __NEED_T_UInt8_NATIVE
