/* C++ Body file for function type FunctionInstance2
 * Generated by TASTE on 2021-05-18 19:10:51
 * You can edit this file, it will not be overwritten
 * Provided interfaces : getPower, setPower
 * Required interfaces : 
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = any
 *   |_ Taste::coordinates = 81498 155101 101581 165025
 *   |_ Taste::is_Instance_Of = Heater::IV::Heater::Heater.others
 *   |_ Taste::is_Instance_Of2 = Heater.others
 * Timers              : 
 */

#include "functioninstance2.h"
#include "heater.h"

// Include Context Parameters (constants defined in the Interface View)
#include "Context-functioninstance2.h"

// Declaration of the function instance
extern heater FunctionInstance2 (functioninstance2_ctxt);

extern "C" void functioninstance2_startup()
{
   FunctionInstance2.startup();
}

extern "C" void functioninstance2_PI_getPower (asn1SccT_Float *power)
{
   FunctionInstance2.getPower(power);
}
extern "C" void functioninstance2_PI_setPower (const asn1SccT_Float *power)
{
   FunctionInstance2.setPower(power);
}
