// Autogenerated code (from TASTE/Kazoo) : DO NOT EDIT
#pragma once
#include "dataview-uniq.h"
#include <assert.h>

typedef enum {
   heattransferlab_f1_max_time, heattransferlab_f2_maz_time
} rpi_partition_1_timer_manager_timers;

static struct {
   long long value;
   enum {active, inactive} state;
} timers[2] = {{ .value = 0, .state = inactive }};

void rpi_partition_1_timer_manager_startup(void);
void rpi_partition_1_timer_manager_PI_Tick(void);

void rpi_partition_1_timer_manager_PI_SET_heattransferlab_f1_max_time(asn1SccT_UInt32 *val);
void rpi_partition_1_timer_manager_PI_RESET_heattransferlab_f1_max_time(void);
void rpi_partition_1_timer_manager_PI_SET_heattransferlab_f2_maz_time(asn1SccT_UInt32 *val);
void rpi_partition_1_timer_manager_PI_RESET_heattransferlab_f2_maz_time(void);

#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
