
/* Header file for function IMU in C language
 * Generated by TASTE on 2021-05-18 13:43:28
 * Context Parameters present : NO
 * Provided interfaces : readAccelData, readGyroData, readMGTdata
 * Required interfaces : 
 * User-defined properties for this function:
  *  |_ Taste::Active_Interfaces = any
  *  |_ Taste::coordinates = 120468 142358 146108 157161
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __unix__
   #include <stdlib.h>
   #include <stdio.h>
#endif

void imu_startup(void);

/* Provided interfaces */
void imu_PI_readAccelData( asn1SccACC_Raw_Data *, asn1SccACC_MilliG_Data * );
void imu_PI_readGyroData( asn1SccGYRO_Raw_Data *, asn1SccGYRO_MilliDPS_Data * );
void imu_PI_readMGTdata( asn1SccMGT_Raw_Data *, asn1SccMGT_MilliGauss_Data * );

/* Required interfaces */



#ifdef __cplusplus
}
#endif
