--  Stub generated by OpenGEODE.
--  You can edit this file, it will not be overwritten

package body Systemhandler_RI is
   procedure stop_DL is null;
   procedure stop_DM is null;
   procedure stop_IIC is null;
end Systemhandler_RI;