/* Body file for function GroundSw
 * Generated by TASTE on 2021-05-17 22:08:25
 * You can edit this file, it will not be overwritten
 * Provided interfaces : sendAllData
 * Required interfaces : 
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = any
 *   |_ Taste::coordinates = 221411 51967 269441 106296
 * Timers              : 
 */

#include "groundsw.h"
//#include <stdio.h>


void groundsw_startup(void)
{
   // Write your initialisation code, but DO NOT CALL REQUIRED INTERFACES
   // puts ("[GroundSw] Startup");
}

void groundsw_PI_sendAllData
      (const asn1SccOBSW_DP_Data *IN_alldata)

{
   // Write your code here
}


