// Body file for function HeatTransferLab
// Generated by TASTE on 2021-05-17 12:48:29
// You can edit this file, it will not be overwritten
// Provided interfaces : 
// Required interfaces : RetreiveHTLData, setPowerH1
// User-defined properties for this function:
//   |_ Taste::Active_Interfaces = any
//   |_ Taste::coordinates = 80815 63778 116033 75692
//   |_ Taste::Fill_Color = #CEFFFF
// Timers              : 

#include "heattransferlab.h"
#include "heattransferlab_state.h"
//#include <iostream>

// Define and use function state inside this context structure
// avoid defining global/static variable elsewhere
heattransferlab_state ctxt_heattransferlab;


void heattransferlab_startup(void)
{
   // Write your initialisation code, but DO NOT CALL REQUIRED INTERFACES
   // std::cout << "[HeatTransferLab] Startup" << std::endl;
}




