/* C++ Body file for function type Heater
 * Generated by TASTE on 2021-05-18 18:06:35
 * You can edit this file, it will not be overwritten
 * Provided interfaces : 
 * Required interfaces : 
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = any
 *   |_ Taste::coordinates = 228132 159379 271421 175976
 *   |_ Taste::is_Component_Type = true
 * Timers              : 
 */

#include "heater.h"
// Include Context Parameters (constants defined in the Interface View)
#include "Context-heater.h"
#include "heater_state.h"

heater_state ctxt_heater;

void heater_startup()
{
   // Write your initialisation code, but DO NOT CALL REQUIRED INTERFACES
   puts ("[Heater] Startup");
}

/* Provided interfaces */
void heater_getPower( asn1SccT_Float * OUT_actualpower ) {
    *OUT_actualpower = ctxt_heater.hh.getActualPower();
}

void heater_setPowerH1( const asn1SccT_Float *IN_power ) {
    ctxt_heater.hh.setPower(*IN_power);
}



