
/* Header file for function Heater in CPP language
 * Generated by TASTE on 2021-05-19 10:36:03
 * Context Parameters present : YES
 * Provided interfaces : getPower, setPowerH1
 * Required interfaces : 
 * User-defined properties for this function:
  *  |_ Taste::Active_Interfaces = any
  *  |_ Taste::coordinates = 78210 146435 108153 159484
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __unix__
   #include <stdlib.h>
   #include <stdio.h>
#endif

void heater_startup(void);

/* Provided interfaces */
void heater_PI_getPower( asn1SccT_Float * );
void heater_PI_setPowerH1( const asn1SccT_Float * );

/* Required interfaces */



#ifdef __cplusplus
}
#endif

