################################################################################
# Name of the static library to be created
NAME_LIB=
# Name of the test BINARY
NAME_TEST=CircularBuffer.t
# Name of the executable
NAME_BIN=
# Additional libraries to be loaded when compiling.
LDLIBS  =-lpthread -lgtest

# If you want to create a librarie add lib, if you want an executable add bin.
.PHONY: all
all: directories lib # <--- add here.

include ../common.mk
################################################################################
