/* Body file for function TC74Sensors
 * Generated by TASTE on 2021-05-17 12:48:29
 * You can edit this file, it will not be overwritten
 * Provided interfaces : readTempsCelsius
 * Required interfaces : 
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = any
 *   |_ Taste::coordinates = 120878 163087 146423 171985
 * Timers              : 
 */

#include "tc74sensors.h"
//#include <stdio.h>


void tc74sensors_startup(void)
{
   // Write your initialisation code, but DO NOT CALL REQUIRED INTERFACES
   // puts ("[TC74Sensors] Startup");
}

void tc74sensors_PI_readTempsCelsius
      (asn1SccTC74s_Celsius_Data *OUT_tempscelsius)

{
   // Write your code here
}


