/* ASN.1 System configuration file for function Heater1
 * Generated by TASTE on 2021-07-08 21:13:24
 */
#define __NEED_Heater_Data_NATIVE
#define __NEED_Heater_On_Off_NATIVE
#define __NEED_T_Float_NATIVE
